# CodeRabbit Configuration for AppLauncher
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language settings
language: ko

# Review settings
reviews:
  # Request changes on critical issues
  request_changes_workflow: true

  # Provide high-level summary
  high_level_summary: true

  # Review each file in detail
  poem: false

  # Provide review summary
  review_status: true

  # Auto-approve PRs
  auto_review:
    enabled: true
    # Don't auto-approve, let human review
    auto_approve: false

  # Labels to apply
  # Auto-apply suggested labels  
  auto_apply_labels: true  
  labeling_instructions:  
    - label: "coderabbit"  
      instructions: "Apply to all PRs reviewed by CodeRabbit"  


# Path-based instructions
path_instructions:
  - path: "**/*.cs"
    instructions: |
      - C# 코딩 컨벤션 준수 확인 (네이밍, 들여쓰기, 중괄호 스타일)
      - null 참조 예외 가능성 확인 (nullable reference types 활용)
      - 리소스 정리 확인 (IDisposable 패턴, using 문 사용)
      - async/await 패턴 올바른 사용 확인 (async void 피하기, ConfigureAwait 고려)
      - 예외 처리 적절성 확인 (빈 catch 블록 지양, 로깅 포함)
      - 매직 넘버/매직 스트링 사용 지양 (상수나 설정으로 분리)

  - path: "**/Features/MqttControl/**/*.cs"
    instructions: |
      - MQTT 연결 상태 관리 확인 (연결/재연결/종료 시나리오)
      - 타이머 리소스 정리 확인 (Dispose 패턴, Stop 후 이벤트 해제)
      - 메시지 직렬화/역직렬화 오류 처리
      - 토픽 이름 관리 (하드코딩 지양)
      - QoS 설정 적절성 확인
      - 비동기 메서드에서 async void 사용 주의 (이벤트 핸들러 제외)
      - 연결 끊김 시나리오 처리 (재연결 로직)

  - path: "**/Features/VersionManagement/**/*.cs"
    instructions: |
      - 파일 다운로드 시 임시 파일 정리 확인
      - HTTP 클라이언트 리소스 관리 (HttpClient 재사용 패턴)
      - 파일 교체 시 권한 문제 처리
      - 업데이트 중 기존 프로세스 종료 처리
      - 롤백 메커니즘 고려
      - 버전 비교 로직 정확성 확인
      - 다운로드 실패 시 재시도 로직
      - 메타데이터 검증 (ProductName, InternalName 등)

  - path: "**/Features/TrayApp/**/*.cs"
    instructions: |
      - UI 스레드 안전성 확인 (Invoke/BeginInvoke 사용)
      - NotifyIcon 리소스 정리 확인
      - 타이머 중복 시작 방지 (Start 전 Stop 확인)
      - 폼 인스턴스 중복 생성 방지 (싱글톤 패턴 또는 null 체크)
      - 애플리케이션 종료 시 모든 리소스 정리
      - 이벤트 핸들러 메모리 누수 확인 (-= 로 해제)
      - 백그라운드 작업 취소 처리

  - path: "**/Features/AppLaunching/**/*.cs"
    instructions: |
      - 프로세스 시작 실패 처리
      - 작업 디렉토리 경로 유효성 검증
      - 프로세스 종료 대기 시간 설정 (무한 대기 방지)
      - 환경 변수 설정 확인
      - 실행 파일 경로 존재 여부 확인
      - 관리자 권한 필요 여부 처리

  - path: "**/Presentation/WinForms/**/*.cs"
    instructions: |
      - UI 스레드 안전성 확인 (Control.InvokeRequired 체크)
      - 폼 리소스 정리 확인 (Dispose 패턴)
      - 사용자 입력 유효성 검사
      - 메시지 박스 과다 사용 지양
      - 긴 작업은 백그라운드 스레드에서 실행
      - 폼 크기/위치 하드코딩 지양
      - 접근성 고려 (TabIndex, 단축키)

  - path: "**/Shared/**/*.cs"
    instructions: |
      - 유틸리티 클래스는 정적 메서드로 구성
      - 재사용성 고려한 설계
      - 의존성 최소화
      - 단위 테스트 가능성 고려
      - 설정 파일 처리 시 JSON 파싱 오류 처리
      - 하드웨어 정보 수집 시 권한 문제 처리

  - path: "**/Shared/Configuration/**/*.cs"
    instructions: |
      - 설정 파일 읽기/쓰기 오류 처리
      - 기본값 제공 (설정 파일 없을 때)
      - 설정 변경 시 유효성 검사
      - 민감 정보 암호화 고려 (비밀번호, 토큰 등)
      - 설정 파일 경로 하드코딩 지양
      - 이전 버전 설정 마이그레이션 고려

  - path: "Program.cs"
    instructions: |
      - 애플리케이션 시작 오류 처리
      - 전역 예외 핸들러 설정
      - 단일 인스턴스 실행 확인 (중복 실행 방지)
      - 애플리케이션 종료 시 정리 작업 확인
      - DPI 인식 설정 확인
      - 콘솔 출력 관리 (릴리즈 빌드에서 제거 고려)

# Knowledge base
knowledge_base:
  opt_out: false
  learnings:
    scope: auto  # 'local', 'global', or 'auto'
    notes:
      - "이 프로젝트는 Windows Forms 기반 C# 애플리케이션이다."
      - "MQTT를 통한 원격 제어 기능을 제공한다."
      - "LabVIEW 애플리케이션 자동 업데이트 및 실행 관리 기능이 있다."
      - ".NET 9.0 타겟 프레임워크를 사용한다."


# Chat settings
chat:
  auto_reply: false
